//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Human_Resources.Metier.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avance
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateVersement { get; set; }
        public Nullable<System.DateTime> Mois { get; set; }
        public Nullable<decimal> Montant { get; set; }
        public Nullable<int> FK_Employe { get; set; }
    
        public virtual Employe Employe { get; set; }
    }
}
