//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Human_Resources.Metier.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BulletinDePaie
    {
        public int Id { get; set; }
        public Nullable<decimal> CNSS { get; set; }
        public Nullable<int> Conges { get; set; }
        public Nullable<System.DateTime> DatePrime { get; set; }
        public Nullable<int> HeuresDeTravail { get; set; }
        public Nullable<int> Nb_H_Ajout { get; set; }
        public Nullable<int> Nb_H_Retard { get; set; }
        public Nullable<decimal> Net_A_Payer { get; set; }
        public Nullable<decimal> Prime_Presence { get; set; }
        public Nullable<decimal> Salaire_Base { get; set; }
        public Nullable<decimal> Salaire_Brute { get; set; }
        public string Statut { get; set; }
        public Nullable<int> FK_Employe { get; set; }
    
        public virtual Employe Employe { get; set; }
    }
}
