//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Human_Resources.Metier.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BulletinDePay
    {
        public int Id { get; set; }
        public Nullable<decimal> CNSS { get; set; }
        public Nullable<int> Conges { get; set; }
        public Nullable<System.DateTime> DatePrime { get; set; }
        public Nullable<int> HeuresDeTravail { get; set; }
        public Nullable<int> Nb_H_Ajout { get; set; }
        public Nullable<int> Nb_H_Retard { get; set; }
        public Nullable<decimal> Net_A_Payer { get; set; }
        public Nullable<decimal> Prime_Presence { get; set; }
        public Nullable<decimal> Salaire_Base { get; set; }
        public Nullable<decimal> Salaire_Brute { get; set; }
        public string Statut { get; set; }
        public int FK_Employe { get; set; }
    
        public virtual Employe Employe { get; set; }
    }
}
