//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Human_Resources.Metier.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChargePatronale
    {
        public int Id { get; set; }
        public Nullable<decimal> CNRPS { get; set; }
        public Nullable<decimal> CNSS { get; set; }
        public Nullable<decimal> IGR { get; set; }
        public Nullable<System.DateTime> Mois { get; set; }
        public Nullable<decimal> Salaires { get; set; }
    }
}
