//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Human_Resources.Metier.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChargePatronale
    {
        public int Id { get; set; }
        public Nullable<decimal> CNRPS { get; set; }
        public Nullable<decimal> CNSS { get; set; }
        public Nullable<decimal> IGR { get; set; }
        public Nullable<System.DateTime> Mois { get; set; }
        public Nullable<decimal> Salaires { get; set; }
    }
}
