//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Human_Resources.Metier.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CNAM
    {
        public int Id { get; set; }
        public Nullable<decimal> TauxPatronal { get; set; }
        public Nullable<decimal> TauxSalarial { get; set; }
        public string Type { get; set; }
    }
}
