//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Human_Resources.Metier.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conge
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateDebut { get; set; }
        public Nullable<System.DateTime> DateDemande { get; set; }
        public Nullable<int> NbreJours { get; set; }
        public string Etat { get; set; }
        public int FK_TypeConge { get; set; }
        public int FK_Employe { get; set; }
    
        public virtual TypeConge TypeConge { get; set; }
        public virtual Employe Employe { get; set; }
    }
}
