//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Human_Resources.Metier.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Departement()
        {
            this.Employes = new HashSet<Employe>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string Libelle { get; set; }
        public byte[] NbreEmployes { get; set; }
        public Nullable<int> Numero { get; set; }
        public int FK_Etablissement { get; set; }
        public int FK_Chef { get; set; }
    
        public virtual Employe Employe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employe> Employes { get; set; }
        public virtual Etablissement Etablissement { get; set; }
    }
}
