//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Human_Resources.Metier.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HumanResourcesEntities : DbContext
    {
        public HumanResourcesEntities()
            : base("name=HumanResourcesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Avance> Avances { get; set; }
        public virtual DbSet<BulletinDePay> BulletinDePaies { get; set; }
        public virtual DbSet<Categorie> Categories { get; set; }
        public virtual DbSet<ChargePatronale> ChargePatronales { get; set; }
        public virtual DbSet<CNAM> CNAMs { get; set; }
        public virtual DbSet<CNRP> CNRPS { get; set; }
        public virtual DbSet<CNSS> CNSSes { get; set; }
        public virtual DbSet<Compte> Comptes { get; set; }
        public virtual DbSet<Conge> Conges { get; set; }
        public virtual DbSet<Contrat> Contrats { get; set; }
        public virtual DbSet<Departement> Departements { get; set; }
        public virtual DbSet<Employe> Employes { get; set; }
        public virtual DbSet<Etablissement> Etablissements { get; set; }
        public virtual DbSet<IGR> IGRs { get; set; }
        public virtual DbSet<InfosBanque> InfosBanques { get; set; }
        public virtual DbSet<LivreDePay> LivreDePaies { get; set; }
        public virtual DbSet<Prime_Categorie> Prime_Categorie { get; set; }
        public virtual DbSet<PrimeFix> PrimeFixes { get; set; }
        public virtual DbSet<PrimesVariable> PrimesVariables { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<TypeConge> TypeConges { get; set; }
        public virtual DbSet<TypeContrat> TypeContrats { get; set; }
    }
}
