//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Human_Resources.Metier.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IGR
    {
        public int Id { get; set; }
        public Nullable<decimal> SalaireMax { get; set; }
        public Nullable<decimal> SalaireMin { get; set; }
        public Nullable<decimal> Taux { get; set; }
    }
}
