//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Human_Resources.Metier.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prime_Categorie
    {
        public int Id { get; set; }
        public Nullable<int> FK_Categorie { get; set; }
        public Nullable<int> FK_PrimeFixe { get; set; }
    
        public virtual Categorie Categorie { get; set; }
        public virtual PrimeFixe PrimeFixe { get; set; }
    }
}
