//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Human_Resources.Metier.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrimesVariable
    {
        public int Id { get; set; }
        public string Libelle { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> Valeur { get; set; }
        public string Exoneres { get; set; }
        public Nullable<System.DateTime> DateAffectation { get; set; }
        public int FK_Employe { get; set; }
    
        public virtual Employe Employe { get; set; }
    }
}
